### PR TITLE
Trivial support for non-parametric types

### PR DESCRIPTION
**Pull request by vlopezj**
Non-plain type variables will be silently ignored.

Type family instantiations within type constructors will be ignored, as
long as they don't involve any of the plain variables.

### CODE REVIEW

**Comment by danr** [comment]
Do you have an updated version for 7.10?

**Comment by vlopezj** [comment]
Done :)

**Comment by danr** [comment]
Thanks, can we get some more comments for further readers and maintenance? In particular:
* a comment on the `Generator` data type of the purpose of `gen_type_inner`
* what `rfr` is in `rfrKinded` and `rfrPlain`. Can they get better names/comment?
* What is the purpose of the `Either TyVarBndr Name`? Should it get an own datatype or a type synonym+comment?
* What's with the two-stage `generate` and `generate'`
* You can remove `tupleDegreeMaybe`, it was only used in `newSanitizedName` (and I approve of your changes to it)
* Also remove the `ddump-splices` comment in `genifunctors.cabal`
Thanks!

**Comment by danr** [comment]
I incorporated your `newSanitizedName` already!

**Pull request closed without merging**
